// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYKAG6k8r8a4_qqew_RRjUcRdGOI_xBRs',
    appId: '1:869860479268:web:b40deee11ff63c7e5423b1',
    messagingSenderId: '869860479268',
    projectId: 'my-money-book',
    authDomain: 'my-money-book.firebaseapp.com',
    storageBucket: 'my-money-book.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPqy80Ui4rM6vbVFXFb0hvdMvZQUCh0N0',
    appId: '1:869860479268:android:9e721bb7cec231d35423b1',
    messagingSenderId: '869860479268',
    projectId: 'my-money-book',
    storageBucket: 'my-money-book.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcHLuyROvIrxyFChOcoMFm2zBthS9M9rE',
    appId: '1:869860479268:ios:7d073f3e0aabce195423b1',
    messagingSenderId: '869860479268',
    projectId: 'my-money-book',
    storageBucket: 'my-money-book.appspot.com',
    iosClientId: '869860479268-nii05p8oir8po0dkspb60sc1u8s8kd1o.apps.googleusercontent.com',
    iosBundleId: 'com.myorg.moneybook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcHLuyROvIrxyFChOcoMFm2zBthS9M9rE',
    appId: '1:869860479268:ios:7d073f3e0aabce195423b1',
    messagingSenderId: '869860479268',
    projectId: 'my-money-book',
    storageBucket: 'my-money-book.appspot.com',
    iosClientId: '869860479268-nii05p8oir8po0dkspb60sc1u8s8kd1o.apps.googleusercontent.com',
    iosBundleId: 'com.myorg.moneybook',
  );
}
